import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const STATES=["DRAFT","RESEARCHING","READY","PRODUCING","REVIEW","APPROVED","QUEUED","PUBLISHED","MONITORED","ARCHIVED"];
const NEXT={DRAFT:"RESEARCHING",RESEARCHING:"READY",READY:"PRODUCING",PRODUCING:"REVIEW",REVIEW:"APPROVED",APPROVED:"QUEUED",QUEUED:"PUBLISHED",PUBLISHED:"MONITORED",MONITORED:"ARCHIVED"};
function App(){const[section,setSection]=useState("Dashboard"),[jobs,setJobs]=useState([{id:"JOB-0001",title:"Bridge Test",type:"SYSTEM",state:"DRAFT",priority:"NORMAL"}]),[selected,setSelected]=useState("JOB-0001"),[events,setEvents]=useState([{id:"AUD-0001",job:"JOB-0001",event:"JOB_CREATED",actor:"MR.ONE",time:"2026-09-29"}]),[approval,setApproval]=useState("NOT_REQUIRED"),[notice,setNotice]=useState("System ready");const job=jobs.find(j=>j.id===selected)||jobs[0];const counts=useMemo(()=>STATES.reduce((a,s)=>(a[s]=jobs.filter(j=>j.state===s).length,a),{}),[jobs]);
function createJob(){const id="JOB-"+String(jobs.length+1).padStart(4,"0"),item={id,title:"New Production Job",type:"GENERAL",state:"DRAFT",priority:"NORMAL"};setJobs(x=>[item,...x]);setSelected(id);setEvents(x=>[{id:"AUD-"+String(x.length+1).padStart(4,"0"),job:id,event:"JOB_CREATED",actor:"MR.ONE",time:new Date().toISOString()},...x]);setNotice(id+" created")}
function transition(){const next=NEXT[job.state];if(!next)return;setJobs(x=>x.map(j=>j.id===job.id?{...j,state:next}:j));setEvents(x=>[{id:"AUD-"+String(x.length+1).padStart(4,"0"),job:job.id,event:"STATE_"+next,actor:"MR.ONE",time:new Date().toISOString()},...x]);if(["APPROVED","PUBLISHED"].includes(next))setApproval("PENDING");setNotice(job.id+" → "+next)}
const nav=["Dashboard","Jobs","Workflow","Approval Gateway","Registry","Audit / History","System Health"];return <div className="app"><aside><div className="brand">MR.ONE<span>Production Engine</span></div><nav>{nav.map(n=><button className={section===n?"active":""} onClick={()=>setSection(n)} key={n}>{n}</button>)}</nav><div className="side-foot">GitHub source of truth<br/>Freebuff runtime</div></aside><main><header><div><div className="eyebrow">CONTROL CENTER</div><h1>{section}</h1></div><button className="primary" onClick={createJob}>+ New Job</button></header><div className="notice">{notice}</div>{section==="Dashboard"&&<Dashboard counts={counts} jobs={jobs} onSelect={setSelected}/>} {section==="Jobs"&&<Jobs jobs={jobs} selected={selected} onSelect={setSelected} onCreate={createJob}/>} {section==="Workflow"&&<Workflow job={job} next={NEXT[job.state]} onTransition={transition}/>} {section==="Approval Gateway"&&<Approval status={approval}/>} {section==="Registry"&&<Registry/>} {section==="Audit / History"&&<Audit events={events}/>} {section==="System Health"&&<Health/>}</main></div>}
function Dashboard({counts,jobs,onSelect}){return <><div className="grid stats">{[["DRAFT","Draft"],["PRODUCING","Producing"],["REVIEW","Review"],["PUBLISHED","Published"]].map(([k,l])=><div className="card stat" key={k}><small>{l}</small><strong>{counts[k]||0}</strong></div>)}</div><div className="card"><div className="card-head"><h2>Active Jobs</h2><span>{jobs.length} total</span></div>{jobs.map(j=><button className="row" key={j.id} onClick={()=>onSelect(j.id)}><b>{j.id}</b><span>{j.title}</span><em>{j.state}</em></button>)}</div></>}
function Jobs({jobs,selected,onSelect,onCreate}){return <div className="card"><div className="card-head"><h2>Job Registry</h2><button onClick={onCreate}>Create test Job</button></div>{jobs.map(j=><button className={"row "+(j.id===selected?"selected":"")} key={j.id} onClick={()=>onSelect(j.id)}><b>{j.id}</b><span>{j.title}</span><em>{j.state}</em></button>)}</div>}
function Workflow({job,next,onTransition}){return <div className="card"><div className="card-head"><h2>Workflow State</h2><span>{job.id}</span></div><div className="state-path">{STATES.map(s=><div className={s===job.state?"current":""} key={s}>{s}</div>)}</div><p>Current state: <b>{job.state}</b></p>{next?<button className="primary" onClick={onTransition}>Transition → {next}</button>:<span className="pill">Terminal state</span>}</div>}
function Approval({status}){return <div className="card"><h2>Approval Gateway</h2><p>Consequential external actions are gated before release.</p><div className="approval"><b>Status</b><span>{status}</span></div></div>}
function Registry(){return <div className="card"><h2>Registry</h2>{["Provider Adapter · LOCAL / MOCK · READY","Storage · LOCAL / MOCK · READY","Distribution · NONE CONNECTED"].map(x=><div className="registry" key={x}>{x}</div>)}</div>}
function Audit({events}){return <div className="card"><h2>Audit / History</h2>{events.map(e=><div className="audit" key={e.id}><b>{e.event}</b><span>{e.job}</span><small>{e.actor} · {e.time}</small></div>)}</div>}
function Health(){return <div className="card"><h2>System Health</h2>{["Application shell · READY","External services · ISOLATED","Secrets in repository · NONE","Distribution adapters · NOT CONNECTED"].map(x=><div className="health" key={x}>{x}</div>)}</div>}
createRoot(document.getElementById("root")).render(<App/>);