import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";

const STATES=["DRAFT","RESEARCHING","READY","PRODUCING","REVIEW","APPROVED","QUEUED","PUBLISHED","MONITORED","ARCHIVED"];
const NEXT={DRAFT:"RESEARCHING",RESEARCHING:"READY",READY:"PRODUCING",PRODUCING:"REVIEW",REVIEW:"APPROVED",APPROVED:"QUEUED",QUEUED:"PUBLISHED",PUBLISHED:"MONITORED",MONITORED:"ARCHIVED"};
const NAV=["Dashboard","Discovery Center","Research","Product","Content","Creative","Queue & Scheduler","Distribution","Monitoring","Analytics","Optimization","Jobs","Workflow","Approval Gateway","Registry","Audit / History","System Health"];
const channels=["INSTAGRAM","FACEBOOK","TIKTOK","YOUTUBE","MARKETPLACE"];
const seedCandidate={id:"CAND-0001",title:"Example Opportunity",source:"USER_URL",url:"https://example.com",evidence:"Seed candidate for integrated pipeline validation.",status:"SAVED",notes:"Replace with verified opportunity."};

function App(){
 const[jobs,setJobs]=useState([{id:"JOB-0001",title:"Integrated Demo Job",type:"GENERAL",state:"DRAFT",priority:"NORMAL",candidateId:"CAND-0001",researchId:"RES-0001",productId:"PROD-0001",contentId:"CONT-0001",creativeId:"CRE-0001"}]);
 const[candidates,setCandidates]=useState([seedCandidate]);
 const[research,setResearch]=useState([{id:"RES-0001",candidateId:"CAND-0001",objective:"Validate opportunity and audience need.",audience:"General social audience",evidence:"Pending source review.",claims:"Claims require evidence mapping.",constraints:"Free-first; no prohibited scraping.",recommendation:"REVIEW",status:"DRAFT",version:1}]);
 const[products,setProducts]=useState([{id:"PROD-0001",researchId:"RES-0001",name:"Example Product Concept",description:"Traceable product concept from research.",specs:"Define after research approval.",version:1,status:"DRAFT",assets:""}]);
 const[contents,setContents]=useState([{id:"CONT-0001",productId:"PROD-0001",master:"Example content master",hooks:"Problem → insight → action",caption:"Draft caption",script:"Draft script",cta:"Learn more",channels:["INSTAGRAM"],version:1,status:"DRAFT"}]);
 const[creatives,setCreatives]=useState([{id:"CRE-0001",contentId:"CONT-0001",storyboard:"Scene 1: Hook\nScene 2: Proof\nScene 3: CTA",prompts:"Visual prompt pending",assets:"",renderStatus:"MOCK_READY",version:1,status:"DRAFT"}]);
 const[queue,setQueue]=useState([{id:"QUEUE-0001",jobId:"JOB-0001",target:"INSTAGRAM",scheduledAt:"",priority:"NORMAL",status:"DRAFT",retryCount:0,approval:"NOT_APPROVED"}]);
 const[publications,setPublications]=useState([]);
 const[events,setEvents]=useState([{id:"AUD-0001",job:"JOB-0001",event:"JOB_CREATED",actor:"MR.ONE",time:new Date().toISOString()}]);
 const[section,setSection]=useState("Dashboard"),[selected,setSelected]=useState("JOB-0001"),[candidateId,setCandidateId]=useState("CAND-0001"),[notice,setNotice]=useState("Full pipeline workspace ready"),[query,setQuery]=useState(""),[filter,setFilter]=useState("ALL");
 const job=jobs.find(x=>x.id===selected)||jobs[0];
 function audit(jobId,event,meta=""){setEvents(x=>[{id:"AUD-"+String(x.length+1).padStart(4,"0"),job:jobId,event,actor:"MR.ONE",time:new Date().toISOString(),meta},...x])}
 function patch(setter,id,patch){setter(x=>x.map(v=>v.id===id?{...v,...patch}:v))}
 function createJob(){const id="JOB-"+String(jobs.length+1).padStart(4,"0");setJobs(x=>[{id,title:"New Production Job",type:"GENERAL",state:"DRAFT",priority:"NORMAL"},...x]);setSelected(id);audit(id,"JOB_CREATED");setNotice(id+" created")}
 function transition(){const next=NEXT[job.state];if(!next)return;setJobs(x=>x.map(v=>v.id===job.id?{...v,state:next}:v));audit(job.id,"STATE_"+next);setNotice(job.id+" → "+next)}
 function createCandidate(){const id="CAND-"+String(candidates.length+1).padStart(4,"0");setCandidates(x=>[{id,title:"New Discovery Candidate",source:"USER_URL",url:"",evidence:"Evidence pending review.",status:"DRAFT",notes:""},...x]);setCandidateId(id);setNotice(id+" created")}
 function handoffCandidate(id){patch(setCandidates,id,{status:"READY_FOR_RESEARCH"});audit(id,"DISCOVERY_HANDOFF_TO_RESEARCH");setNotice(id+" → Research")}
 function createResearch(){const id="RES-"+String(research.length+1).padStart(4,"0");setResearch(x=>[{id,candidateId,objective:"",audience:"",evidence:"",claims:"",constraints:"",recommendation:"",status:"DRAFT",version:1},...x]);setNotice(id+" created")}
 function createProduct(){const id="PROD-"+String(products.length+1).padStart(4,"0");setProducts(x=>[{id,researchId:research[0]?.id||"",name:"New Product Concept",description:"",specs:"",version:1,status:"DRAFT",assets:""},...x]);setNotice(id+" created")}
 function createContent(){const id="CONT-"+String(contents.length+1).padStart(4,"0");setContents(x=>[{id,productId:products[0]?.id||"",master:"",hooks:"",caption:"",script:"",cta:"",channels:["INSTAGRAM"],version:1,status:"DRAFT"},...x]);setNotice(id+" created")}
 function createCreative(){const id="CRE-"+String(creatives.length+1).padStart(4,"0");setCreatives(x=>[{id,contentId:contents[0]?.id||"",storyboard:"",prompts:"",assets:"",renderStatus:"MOCK_READY",version:1,status:"DRAFT"},...x]);setNotice(id+" created")}
 function createQueue(){const id="QUEUE-"+String(queue.length+1).padStart(4,"0");setQueue(x=>[{id,jobId:selected,target:"INSTAGRAM",scheduledAt:"",priority:"NORMAL",status:"DRAFT",retryCount:0,approval:"NOT_APPROVED"},...x]);setNotice(id+" created")}
 function approveQueue(id){patch(setQueue,id,{approval:"APPROVED",status:"READY"});audit(selected,"QUEUE_APPROVED",id);setNotice(id+" approved")}
 function mockPublish(q){if(q.approval!=="APPROVED"){setNotice("Approval required before distribution");return}const p={id:"PUB-"+String(publications.length+1).padStart(4,"0"),queueId:q.id,destination:q.target,externalId:"MOCK-"+Date.now(),publishedAt:new Date().toISOString(),result:"MOCK_SUCCESS",error:""};setPublications(x=>[p,...x]);patch(setQueue,q.id,{status:"PUBLISHED"});audit(q.jobId,"MOCK_PUBLICATION_SUCCESS",q.target);setNotice(q.id+" published in mock adapter")}
 const counts=useMemo(()=>STATES.reduce((a,s)=>(a[s]=jobs.filter(j=>j.state===s).length,a),{}),[jobs]);
 const action=section==="Discovery Center"?createCandidate:section==="Research"?createResearch:section==="Product"?createProduct:section==="Content"?createContent:section==="Creative"?createCreative:section==="Queue & Scheduler"?createQueue:createJob;
 return <div className="app"><aside><div className="brand">MR.ONE<span>Production Engine</span></div><nav>{NAV.map(n=><button className={section===n?"active":""} onClick={()=>setSection(n)} key={n}>{n}</button>)}</nav><div className="side-foot">GitHub source of truth<br/>Freebuff final validation</div></aside><main><header><div><div className="eyebrow">CONTROL CENTER · FULL PIPELINE</div><h1>{section}</h1></div><button className="primary" onClick={action}>{section==="Discovery Center"?"+ Candidate":section==="Research"?"+ Research":section==="Product"?"+ Product":section==="Content"?"+ Content":section==="Creative"?"+ Creative":section==="Queue & Scheduler"?"+ Queue":section.startsWith("Dashboard")?"+ Job":"+ New Job"}</button></header><div className="notice">{notice}</div>
 {section==="Dashboard"&&<Dashboard counts={counts} jobs={jobs} setSection={setSection} setSelected={setSelected} candidates={candidates} queue={queue} publications={publications}/>}
 {section==="Discovery Center"&&<Discovery data={candidates} selected={candidateId} setSelected={setCandidateId} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} update={(id,p)=>patch(setCandidates,id,p)} handoff={handoffCandidate}/>}
 {section==="Research"&&<Research data={research} update={(id,p)=>patch(setResearch,id,p)}/>}
 {section==="Product"&&<Product data={products} update={(id,p)=>patch(setProducts,id,p)}/>}
 {section==="Content"&&<Content data={contents} update={(id,p)=>patch(setContents,id,p)}/>}
 {section==="Creative"&&<Creative data={creatives} update={(id,p)=>patch(setCreatives,id,p)}/>}
 {section==="Queue & Scheduler"&&<Queue data={queue} update={(id,p)=>patch(setQueue,id,p)} approve={approveQueue} publish={mockPublish}/>}
 {section==="Distribution"&&<Distribution publications={publications} queue={queue} publish={mockPublish}/>}
 {section==="Monitoring"&&<Monitoring jobs={jobs} queue={queue} publications={publications}/>}
 {section==="Analytics"&&<Analytics jobs={jobs} queue={queue} publications={publications} candidates={candidates}/>}
 {section==="Optimization"&&<Optimization jobs={jobs} queue={queue} contents={contents}/>}
 {section==="Jobs"&&<Jobs jobs={jobs} selected={selected} setSelected={setSelected} create={createJob}/>}
 {section==="Workflow"&&<Workflow job={job} next={NEXT[job.state]} transition={transition}/>}
 {section==="Approval Gateway"&&<Approval queue={queue}/>}
 {section==="Registry"&&<Registry/>}{section==="Audit / History"&&<Audit events={events}/>}
 {section==="System Health"&&<Health/>}</main></div>
}

function Dashboard({counts,jobs,setSection,setSelected,candidates,queue,publications}){return <><div className="grid stats">{[["DRAFT","Draft"],["RESEARCHING","Research"],["PRODUCING","Producing"],["PUBLISHED","Published"]].map(([k,l])=><div className="card stat" key={k}><small>{l}</small><strong>{counts[k]||0}</strong></div>)}</div><div className="grid two"><div className="card"><div className="card-head"><h2>Pipeline</h2><span>Integrated</span></div>{["Discovery","Research","Product","Content","Creative","Queue","Distribution","Monitoring","Analytics","Optimization"].map((x,i)=><button className="pipeline" key={x} onClick={()=>setSection(x==="Queue"?"Queue & Scheduler":x)}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><em>{i<2?"READY":"MOCK / READY"}</em></button>)}</div><div className="card"><h2>System Snapshot</h2><div className="health">Candidates <b>{candidates.length}</b></div><div className="health">Jobs <b>{jobs.length}</b></div><div className="health">Queue items <b>{queue.length}</b></div><div className="health">Publications <b>{publications.length}</b></div><p className="muted">All external providers remain isolated behind adapters.</p></div></div></>}
function Discovery({data,selected,setSelected,query,setQuery,filter,setFilter,update,handoff}){const visible=data.filter(c=>(filter==="ALL"||c.status===filter)&&((c.title+c.source+c.evidence).toLowerCase().includes(query.toLowerCase())));const c=data.find(x=>x.id===selected)||visible[0];return <><ListCard title="Opportunity Discovery" count={data.length}><div className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search..."/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>ALL</option><option>SAVED</option><option>DRAFT</option><option>ARCHIVED</option><option>READY_FOR_RESEARCH</option></select></div>{visible.map(x=><button className={"row "+(x.id===selected?"selected":"")} key={x.id} onClick={()=>setSelected(x.id)}><b>{x.id}</b><span>{x.title}<small>{x.source}</small></span><em>{x.status}</em></button>)}</ListCard>{c&&<Editor title={c.id} fields={[["title","Title"],["url","Source URL"],["evidence","Evidence"],["notes","Notes"]]} item={c} update={update} actions={<><button onClick={()=>update(c.id,{status:"SAVED"})}>Save</button><button onClick={()=>update(c.id,{status:"ARCHIVED"})}>Archive</button><button className="primary" disabled={!c.url||!c.evidence} onClick={()=>handoff(c.id)}>Handoff → Research</button></>}/>}</>}
function Research({data,update}){const x=data[0];return <><ListCard title="Research Engine" count={data.length}>{data.map(r=><div className="row static" key={r.id}><b>{r.id}</b><span>{r.objective||"Research brief"}</span><em>{r.status}</em></div>)}</ListCard>{x&&<Editor title={x.id+" · Research Brief"} fields={[["objective","Objective"],["audience","Audience"],["evidence","Evidence"],["claims","Claims / Evidence Map"],["constraints","Constraints"],["recommendation","Recommendation"]]} item={x} update={update}/>}</>}
function Product({data,update}){const x=data[0];return <><ListCard title="Product Engine" count={data.length}>{data.map(p=><div className="row static" key={p.id}><b>{p.id}</b><span>{p.name}</span><em>{p.status}</em></div>)}</ListCard>{x&&<Editor title={x.id+" · Product Record"} fields={[["name","Name"],["description","Description"],["specs","Specifications"],["assets","Assets / References"]]} item={x} update={update}/>}</>}
function Content({data,update}){const x=data[0];return <><ListCard title="Content Engine" count={data.length}>{data.map(c=><div className="row static" key={c.id}><b>{c.id}</b><span>{c.master||"Content Master"}</span><em>{c.status}</em></div>)}</ListCard>{x&&<Editor title={x.id+" · Content Master"} fields={[["master","Master Text"],["hooks","Hooks"],["caption","Caption"],["script","Script"],["cta","CTA"]]} item={x} update={update}/>}</>}
function Creative({data,update}){const x=data[0];return <><ListCard title="Creative Engine" count={data.length}>{data.map(c=><div className="row static" key={c.id}><b>{c.id}</b><span>{c.renderStatus}</span><em>{c.status}</em></div>)}</ListCard>{x&&<Editor title={x.id+" · Creative Brief"} fields={[["storyboard","Storyboard"],["prompts","Image / Video Prompts"],["assets","Asset Registry"]]} item={x} update={update}/>}</>}
function Queue({data,update,approve,publish}){return <ListCard title="Queue & Scheduler" count={data.length}>{data.map(q=><div className="queue-item" key={q.id}><div><b>{q.id}</b><span>{q.target} · {q.scheduledAt||"unscheduled"} · {q.status}</span></div><div className="actions"><button onClick={()=>update(q.id,{scheduledAt:new Date().toISOString()})}>Schedule</button><button onClick={()=>approve(q.id)}>Approve</button><button className="primary" onClick={()=>publish(q)}>Mock Publish</button></div></div>)}</ListCard>}
function Distribution({publications,queue,publish}){return <><div className="card"><h2>Distribution Adapters</h2><p className="muted">Provider-neutral boundary. No live credentials are connected.</p>{channels.map(c=><div className="health" key={c}><b>{c}</b><span> NOT CONNECTED · MOCK ADAPTER READY</span></div>)}</div><ListCard title="Publication Results" count={publications.length}>{publications.map(p=><div className="row static" key={p.id}><b>{p.id}</b><span>{p.destination} · {p.externalId}</span><em>{p.result}</em></div>)}</ListCard></>}
function Monitoring({jobs,queue,publications}){return <div className="card"><h2>Monitoring</h2><div className="health">Jobs <b>{jobs.length}</b></div><div className="health">Queue ready <b>{queue.filter(q=>q.status==="READY").length}</b></div><div className="health">Published <b>{publications.length}</b></div><div className="health">Failures <b>0</b></div><p className="muted">Provider responses and errors will be attached to Publication records by adapters.</p></div>}
function Analytics({jobs,queue,publications,candidates}){return <div className="grid two"><div className="card"><h2>Production Metrics</h2><Metric label="Candidates" value={candidates.length}/><Metric label="Jobs" value={jobs.length}/><Metric label="Queue items" value={queue.length}/><Metric label="Publications" value={publications.length}/></div><div className="card"><h2>Distribution Metrics</h2><Metric label="Mock success rate" value={publications.length?"100%":"—"}/><Metric label="Retries" value="0"/><Metric label="External provider attribution" value="N/A"/></div></div>}
function Optimization({jobs,queue,contents}){return <div className="card"><h2>Optimization / Bounded Assistance</h2><div className="recommend">Opportunity routing <b>{jobs.length?"Ready":"Waiting for jobs"}</b></div><div className="recommend">Queue prioritization <b>{queue.length?"Ready":"No queue"}</b></div><div className="recommend">Content reuse <b>{contents.length>1?"Available":"Seed only"}</b></div><p className="muted">Recommendations are advisory, auditable, reversible, and do not autonomously control external platforms.</p></div>}
function Jobs({jobs,selected,setSelected,create}){return <ListCard title="Job Registry" count={jobs.length}><div className="card-head"><button onClick={create}>Create Job</button></div>{jobs.map(j=><button className={"row "+(j.id===selected?"selected":"")} key={j.id} onClick={()=>setSelected(j.id)}><b>{j.id}</b><span>{j.title}</span><em>{j.state}</em></button>)}</ListCard>}
function Workflow({job,next,transition}){return <div className="card"><h2>Workflow State · {job.id}</h2><div className="state-path">{STATES.map(s=><div className={s===job.state?"current":""} key={s}>{s}</div>)}</div><p>Current: <b>{job.state}</b></p>{next?<button className="primary" onClick={transition}>Transition → {next}</button>:<span className="pill">Terminal</span>}</div>}
function Approval({queue}){return <div className="card"><h2>Approval Gateway</h2><p className="muted">Consequential external actions require explicit approval.</p>{queue.map(q=><div className="approval" key={q.id}><b>{q.id}</b><span>{q.approval} · {q.target}</span></div>)}</div>}
function Registry(){return <div className="card"><h2>Registry / Adapter Matrix</h2>{["Research · LOCAL / MOCK · READY","Product · LOCAL / MOCK · READY","Content · LOCAL / MOCK · READY","Creative · LOCAL / MOCK · READY","Storage · LOCAL / MOCK · REPLACEABLE","Instagram · NOT CONNECTED · ADAPTER READY","Facebook · NOT CONNECTED · ADAPTER READY","TikTok · NOT CONNECTED · ADAPTER READY","YouTube · NOT CONNECTED · ADAPTER READY","Marketplace · NOT CONNECTED · ADAPTER READY"].map(x=><div className="registry" key={x}>{x}</div>)}</div>}
function Audit({events}){return <div className="card"><h2>Audit / History</h2>{events.map(e=><div className="audit" key={e.id}><b>{e.event}</b><span>{e.job}</span><small>{e.actor} · {e.time}</small></div>)}</div>}
function Health(){return <div className="card"><h2>System Health</h2>{["Application shell · READY","Discovery → Optimization · INTEGRATED MOCK PATH","Secrets in repository · NONE","External providers · ISOLATED","Live distribution · NOT CONNECTED","Approval gateway · ENABLED","Audit trail · ENABLED"].map(x=><div className="health" key={x}>{x}</div>)}</div>}
function ListCard({title,count,children}){return <div className="card"><div className="card-head"><h2>{title}</h2><span>{count} records</span></div>{children}</div>}
function Editor({title,fields,item,update,actions}){return <div className="card"><div className="card-head"><h2>{title}</h2><span>editable mock state</span></div>{fields.map(([k,l])=><label key={k}>{l}{k==="url"?<input value={item[k]||""} onChange={e=>update(item.id,{[k]:e.target.value})}/>:<textarea value={item[k]||""} onChange={e=>update(item.id,{[k]:e.target.value})}/>}</label>)}{actions&&<div className="actions">{actions}</div>}</div>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}

createRoot(document.getElementById("root")).render(<App/>);