import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const STATES=["DRAFT","RESEARCHING","READY","PRODUCING","REVIEW","APPROVED","QUEUED","PUBLISHED","MONITORED","ARCHIVED"];
const NEXT={DRAFT:"RESEARCHING",RESEARCHING:"READY",READY:"PRODUCING",PRODUCING:"REVIEW",REVIEW:"APPROVED",APPROVED:"QUEUED",QUEUED:"PUBLISHED",PUBLISHED:"MONITORED",MONITORED:"ARCHIVED"};
const DISCOVERY=["MARKETPLACE","PUBLIC_CONTENT","APPROVED_NEWS","USER_URL"];
const seed=[{id:"CAND-0001",title:"Example Opportunity",source:"USER_URL",url:"https://example.com",evidence:"Seed candidate for Discovery Center acceptance testing.",status:"SAVED",notes:"Replace with a verified opportunity."}];
function App(){const[section,setSection]=useState("Dashboard"),[jobs,setJobs]=useState([{id:"JOB-0001",title:"Bridge Test",type:"SYSTEM",state:"DRAFT",priority:"NORMAL"}]),[selected,setSelected]=useState("JOB-0001"),[events,setEvents]=useState([{id:"AUD-0001",job:"JOB-0001",event:"JOB_CREATED",actor:"MR.ONE",time:"2026-09-29"}]),[approval,setApproval]=useState("NOT_REQUIRED"),[notice,setNotice]=useState("System ready"),[candidates,setCandidates]=useState(seed),[candidateId,setCandidateId]=useState("CAND-0001"),[query,setQuery]=useState(""),[filter,setFilter]=useState("ALL");
const job=jobs.find(j=>j.id===selected)||jobs[0],counts=useMemo(()=>STATES.reduce((a,s)=>(a[s]=jobs.filter(j=>j.state===s).length,a),{}),[jobs]);
function audit(jobId,event){setEvents(x=>[{id:"AUD-"+String(x.length+1).padStart(4,"0"),job:jobId,event,actor:"MR.ONE",time:new Date().toISOString()},...x])}
function createJob(){const id="JOB-"+String(jobs.length+1).padStart(4,"0");setJobs(x=>[{id,title:"New Production Job",type:"GENERAL",state:"DRAFT",priority:"NORMAL"},...x]);setSelected(id);audit(id,"JOB_CREATED");setNotice(id+" created")}
function transition(){const next=NEXT[job.state];if(!next)return;setJobs(x=>x.map(j=>j.id===job.id?{...j,state:next}:j));audit(job.id,"STATE_"+next);if(["APPROVED","PUBLISHED"].includes(next))setApproval("PENDING");setNotice(job.id+" → "+next)}
function createCandidate(){const id="CAND-"+String(candidates.length+1).padStart(4,"0");setCandidates(x=>[{id,title:"New Discovery Candidate",source:"USER_URL",url:"",evidence:"Evidence pending review.",status:"DRAFT",notes:""},...x]);setCandidateId(id);setNotice(id+" created")}
function updateCandidate(id,patch){setCandidates(x=>x.map(c=>c.id===id?{...c,...patch}:c))}
function handoff(id){updateCandidate(id,{status:"READY_FOR_RESEARCH"});audit(id,"DISCOVERY_HANDOFF_TO_RESEARCH");setNotice(id+" handed to Research")}
const nav=["Dashboard","Discovery Center","Jobs","Workflow","Approval Gateway","Registry","Audit / History","System Health"];
return <div className="app"><aside><div className="brand">MR.ONE<span>Production Engine</span></div><nav>{nav.map(n=><button className={section===n?"active":""} onClick={()=>setSection(n)} key={n}>{n}</button>)}</nav><div className="side-foot">GitHub source of truth<br/>Freebuff runtime</div></aside><main><header><div><div className="eyebrow">CONTROL CENTER</div><h1>{section}</h1></div><button className="primary" onClick={section==="Discovery Center"?createCandidate:createJob}>{section==="Discovery Center"?"+ New Candidate":"+ New Job"}</button></header><div className="notice">{notice}</div>
{section==="Dashboard"&&<Dashboard counts={counts} jobs={jobs} onSelect={setSelected}/>}
{section==="Discovery Center"&&<Discovery candidates={candidates} candidateId={candidateId} setCandidateId={setCandidateId} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} onCreate={createCandidate} onUpdate={updateCandidate} onHandoff={handoff}/>}
{section==="Jobs"&&<Jobs jobs={jobs} selected={selected} onSelect={setSelected} onCreate={createJob}/>}
{section==="Workflow"&&<Workflow job={job} next={NEXT[job.state]} onTransition={transition}/>}
{section==="Approval Gateway"&&<Approval status={approval}/>}
{section==="Registry"&&<Registry/>}{section==="Audit / History"&&<Audit events={events}/>}
{section==="System Health"&&<Health/>}</main></div>}
function Dashboard({counts,jobs,onSelect}){return <><div className="grid stats">{[["DRAFT","Draft"],["PRODUCING","Producing"],["REVIEW","Review"],["PUBLISHED","Published"]].map(([k,l])=><div className="card stat" key={k}><small>{l}</small><strong>{counts[k]||0}</strong></div>)}</div><div className="card"><div className="card-head"><h2>Active Jobs</h2><span>{jobs.length} total</span></div>{jobs.map(j=><button className="row" key={j.id} onClick={()=>onSelect(j.id)}><b>{j.id}</b><span>{j.title}</span><em>{j.state}</em></button>)}</div></>}
function Discovery({candidates,candidateId,setCandidateId,query,setQuery,filter,setFilter,onCreate,onUpdate,onHandoff}){const visible=candidates.filter(c=>(filter==="ALL"||c.status===filter)&&((c.title+c.source+c.evidence).toLowerCase().includes(query.toLowerCase())));const c=candidates.find(x=>x.id===candidateId)||visible[0];return <><div className="card"><div className="card-head"><h2>Opportunity Discovery</h2><span>{candidates.length} candidates</span></div><div className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search candidates..."/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>ALL</option><option>SAVED</option><option>DRAFT</option><option>ARCHIVED</option><option>READY_FOR_RESEARCH</option></select></div>{visible.map(x=><button className={"row "+(x.id===candidateId?"selected":"")} key={x.id} onClick={()=>setCandidateId(x.id)}><b>{x.id}</b><span>{x.title}<small>{x.source}</small></span><em>{x.status}</em></button>)}</div>{c&&<div className="card"><div className="card-head"><h2>{c.id}</h2><span>{c.source}</span></div><label>Title<input value={c.title} onChange={e=>onUpdate(c.id,{title:e.target.value})}/></label><label>Source URL<input value={c.url} onChange={e=>onUpdate(c.id,{url:e.target.value})} placeholder="https://..."/></label><label>Evidence<textarea value={c.evidence} onChange={e=>onUpdate(c.id,{evidence:e.target.value})}/></label><label>Notes<textarea value={c.notes} onChange={e=>onUpdate(c.id,{notes:e.target.value})}/></label><div className="actions"><button onClick={()=>onUpdate(c.id,{status:"SAVED"})}>Save</button><button onClick={()=>onUpdate(c.id,{status:"ARCHIVED"})}>Archive</button><button className="primary" onClick={()=>onHandoff(c.id)} disabled={!c.url||!c.evidence}>Handoff → Research</button></div></div>}</>}
function Jobs({jobs,selected,onSelect,onCreate}){return <div className="card"><div className="card-head"><h2>Job Registry</h2><button onClick={onCreate}>Create test Job</button></div>{jobs.map(j=><button className={"row "+(j.id===selected?"selected":"")} key={j.id} onClick={()=>onSelect(j.id)}><b>{j.id}</b><span>{j.title}</span><em>{j.state}</em></button>)}</div>}
function Workflow({job,next,onTransition}){return <div className="card"><div className="card-head"><h2>Workflow State</h2><span>{job.id}</span></div><div className="state-path">{STATES.map(s=><div className={s===job.state?"current":""} key={s}>{s}</div>)}</div><p>Current state: <b>{job.state}</b></p>{next?<button className="primary" onClick={onTransition}>Transition → {next}</button>:<span className="pill">Terminal state</span>}</div>}
function Approval({status}){return <div className="card"><h2>Approval Gateway</h2><p>Consequential external actions are gated before release.</p><div className="approval"><b>Status</b><span>{status}</span></div></div>}
function Registry(){return <div className="card"><h2>Registry</h2>{["Provider Adapter · LOCAL / MOCK · READY","Storage · LOCAL / MOCK · READY","Distribution · NONE CONNECTED"].map(x=><div className="registry" key={x}>{x}</div>)}</div>}
function Audit({events}){return <div className="card"><h2>Audit / History</h2>{events.map(e=><div className="audit" key={e.id}><b>{e.event}</b><span>{e.job}</span><small>{e.actor} · {e.time}</small></div>)}</div>}
function Health(){return <div className="card"><h2>System Health</h2>{["Application shell · READY","Discovery Center · LOCAL / MOCK","External services · ISOLATED","Secrets in repository · NONE","Distribution adapters · NOT CONNECTED"].map(x=><div className="health" key={x}>{x}</div>)}</div>}
createRoot(document.getElementById("root")).render(<App/>);